### ISSUE TITLE
Fails to upgrade to  6.0.1~ynh1

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/wordpress_ynh#184]
Here is the log https://paste.yunohost.org/raw/oqifenohun

From what I read there is an issue with some (or at leas one) plugins. But I see other errors such as 
```
PHP Fatal error:  Uncaught Error: Call to undefined function wp_generate_password() in /var/www/wordpress__4/wp-admin/includes/file.php:677

2022-09-02 02:06:35,751: WARNING - #0 /var/www/wordpress__4/wp-admin/includes/class-wp-filesystem-ftpext.php(138): wp_tempnam()
```
I upgraded multiple WP websites and all good. So any idea what's the issue?

**Comment by kay0u** [comment]
In your `wp-config.php` do you have something like:
```
define( 'FS_METHOD', 'ftpext' );
```

Because the plugin `responsive-menu` tries to get content from a FTP
```
PHP Fatal error:  Uncaught Error: Call to undefined function wp_generate_password() in /var/www/wordpress__4/wp-admin/includes/file.php:677
Stack trace:
#0 /var/www/wordpress__4/wp-admin/includes/class-wp-filesystem-ftpext.php(138): wp_tempnam()
#1 /var/www/wordpress__4/wp-content/plugins/responsive-menu/v4.0.0/inc/classes/class-theme-manager.php(436): WP_Filesystem_FTPext->get_contents()
#2 /var/www/wordpress__4/wp-content/plugins/responsive-menu/v4.0.0/inc/classes/class-theme-manager.php(850): RMP\Features\Inc\Theme_Manager->get_themes_from_uploads()
#3 /var/www/wordpress__4/wp-content/plugins/responsive-menu/responsive-menu.php(170): RMP\Features\Inc\Theme_Manager->get_menu_active_themes()
#4 /var/www/wordpress__4/wp-content/plugins/responsive-menu/responsive-menu.php(185): rm_includes_menu_theme_template()
#5 /var/www/wordpress__4/wp-settings.php(428): include_once('/var/www/wordpr...')
#6 phar:///var/www/wordpress__4/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1317): require('/var/www/wordpr...')
#7 phar:///var in /var/www/wordpress__4/wp-admin/includes/file.php on line 677
```
If yes, can you remove this line? If not, can you update your plugins via the admin panel of wordpress?

Edit: [a link](https://www.wpoptimus.com/555/2-ways-skip-ftp-credentials-window-wordpress/) to help you to configure the FTP

**Comment by tio-trom** [comment]
Thank you very much!

I did not have that in wp-config.php and all of my plugins were up to date, but I simply deactivated that plugin and all worked fine. I reactivated after. Thanks again!
