### ISSUE TITLE
Can not update 6.0.2~ynh1 nach 6.0.2~ynh2

### ISSUE THREAD

**Issue by vsatmydynipnet** [YunoHost-Apps/wordpress_ynh#198]
Thank you for any help

LOG :
-------------------------------------------------------
```
Activating maintenance mode...
Ensuring downward compatibility...
PHP Fatal error: Uncaught TypeError: ftp_fget(): Argument #1 ($ftp) must be of type resource, null given in /var/www/wordpress/wp-admin/includes/class-wp-filesystem-ftpext.php:146
Stack trace:
#0 /var/www/wordpress/wp-admin/includes/class-wp-filesystem-ftpext.php(146): ftp_fget()
#1 /var/www/wordpress/wp-content/plugins/premiex-common/redux-framework-master/sample/sample-config.php(30): WP_Filesystem_FTPext->get_contents()
#2 /var/www/wordpress/wp-content/plugins/premiex-common/premiex-common.php(13): include('...')
#3 /var/www/wordpress/wp-settings.php(428): include_once('...')
#4 phar:///var/www/wordpress/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1336): require('...')
#5 phar:///var/www/wordpress/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1254): WP_CLI\Runner->load_wordpress()
#6 phar:///var/www/wordpress/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#7 phar:///var/www/wordpress/wp-cli.phar/vendor/wp-cli/wp-cli/php/bootstrap.php(78): WP_CLI\Bootstrap\LaunchRunner->process()
#8 phar:///var/www/wordpress/wp-cli.phar/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
#9 phar:///var/www/wordpress/wp-cli.phar/php/boot-phar.php(11): include('...')
#10 /var/www/wordpress/wp-cli.phar(4): include('...')
#11 {main}
thrown in /var/www/wordpress/wp-admin/includes/class-wp-filesystem-ftpext.php on line 146
Fatal error: Uncaught TypeError: ftp_fget(): Argument #1 ($ftp) must be of type resource, null given in /var/www/wordpress/wp-admin/includes/class-wp-filesystem-ftpext.php:146
Stack trace:
#0 /var/www/wordpress/wp-admin/includes/class-wp-filesystem-ftpext.php(146): ftp_fget()
#1 /var/www/wordpress/wp-content/plugins/premiex-common/redux-framework-master/sample/sample-config.php(30): WP_Filesystem_FTPext->get_contents()
#2 /var/www/wordpress/wp-content/plugins/premiex-common/premiex-common.php(13): include('...')
#3 /var/www/wordpress/wp-settings.php(428): include_once('...')
#4 phar:///var/www/wordpress/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1336): require('...')
#5 phar:///var/www/wordpress/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1254): WP_CLI\Runner->load_wordpress()
#6 phar:///var/www/wordpress/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#7 phar:///var/www/wordpress/wp-cli.phar/vendor/wp-cli/wp-cli/php/bootstrap.php(78): WP_CLI\Bootstrap\LaunchRunner->process()
#8 phar:///var/www/wordpress/wp-cli.phar/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
#9 phar:///var/www/wordpress/wp-cli.phar/php/boot-phar.php(11): include('...')
#10 /var/www/wordpress/wp-cli.phar(4): include('...')
#11 {main}
thrown in /var/www/wordpress/wp-admin/includes/class-wp-filesystem-ftpext.php on line 146
Error: There has been a critical error on this website.Learn more about troubleshooting WordPress. There has been a critical error on this website.
PHP Fatal error: Uncaught TypeError: ftp_fget(): Argument #1 ($ftp) must be of type resource, null given in /var/www/wordpress/wp-admin/includes/class-wp-filesystem-ftpext.php:146
Stack trace:
#0 /var/www/wordpress/wp-admin/includes/class-wp-filesystem-ftpext.php(146): ftp_fget()
#1 /var/www/wordpress/wp-content/plugins/premiex-common/redux-framework-master/sample/sample-config.php(30): WP_Filesystem_FTPext->get_contents()
#2 /var/www/wordpress/wp-content/plugins/premiex-common/premiex-common.php(13): include('...')
#3 /var/www/wordpress/wp-settings.php(428): include_once('...')
#4 phar:///var/www/wordpress/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1336): require('...')
#5 phar:///var/www/wordpress/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1254): WP_CLI\Runner->load_wordpress()
#6 phar:///var/www/wordpress/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#7 phar:///var/www/wordpress/wp-cli.phar/vendor/wp-cli/wp-cli/php/bootstrap.php(78): WP_CLI\Bootstrap\LaunchRunner->process()
#8 phar:///var/www/wordpress/wp-cli.phar/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
#9 phar:///var/www/wordpress/wp-cli.phar/php/boot-phar.php(11): include('...')
#10 /var/www/wordpress/wp-cli.phar(4): include('...')
#11 {main}
thrown in /var/www/wordpress/wp-admin/includes/class-wp-filesystem-ftpext.php on line 146
Fatal error: Uncaught TypeError: ftp_fget(): Argument #1 ($ftp) must be of type resource, null given in /var/www/wordpress/wp-admin/includes/class-wp-filesystem-ftpext.php:146
Stack trace:
#0 /var/www/wordpress/wp-admin/includes/class-wp-filesystem-ftpext.php(146): ftp_fget()
#1 /var/www/wordpress/wp-content/plugins/premiex-common/redux-framework-master/sample/sample-config.php(30): WP_Filesystem_FTPext->get_contents()
#2 /var/www/wordpress/wp-content/plugins/premiex-common/premiex-common.php(13): include('...')
#3 /var/www/wordpress/wp-settings.php(428): include_once('...')
#4 phar:///var/www/wordpress/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1336): require('...')
#5 phar:///var/www/wordpress/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1254): WP_CLI\Runner->load_wordpress()
#6 phar:///var/www/wordpress/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#7 phar:///var/www/wordpress/wp-cli.phar/vendor/wp-cli/wp-cli/php/bootstrap.php(78): WP_CLI\Bootstrap\LaunchRunner->process()
#8 phar:///var/www/wordpress/wp-cli.phar/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
#9 phar:///var/www/wordpress/wp-cli.phar/php/boot-phar.php(11): include('...')
#10 /var/www/wordpress/wp-cli.phar(4): include('...')
#11 {main}
thrown in /var/www/wordpress/wp-admin/includes/class-wp-filesystem-ftpext.php on line 146
Error: There has been a critical error on this website.Learn more about troubleshooting WordPress. There has been a critical error on this website.
PHP Fatal error: Uncaught TypeError: ftp_fget(): Argument #1 ($ftp) must be of type resource, null given in /var/www/wordpress/wp-admin/includes/class-wp-filesystem-ftpext.php:146
Stack trace:
#0 /var/www/wordpress/wp-admin/includes/class-wp-filesystem-ftpext.php(146): ftp_fget()
#1 /var/www/wordpress/wp-content/plugins/premiex-common/redux-framework-master/sample/sample-config.php(30): WP_Filesystem_FTPext->get_contents()
#2 /var/www/wordpress/wp-content/plugins/premiex-common/premiex-common.php(13): include('...')
#3 /var/www/wordpress/wp-settings.php(428): include_once('...')
#4 phar:///var/www/wordpress/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1336): require('...')
#5 phar:///var/www/wordpress/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1254): WP_CLI\Runner->load_wordpress()
#6 phar:///var/www/wordpress/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#7 phar:///var/www/wordpress/wp-cli.phar/vendor/wp-cli/wp-cli/php/bootstrap.php(78): WP_CLI\Bootstrap\LaunchRunner->process()
#8 phar:///var/www/wordpress/wp-cli.phar/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
#9 phar:///var/www/wordpress/wp-cli.phar/php/boot-phar.php(11): include('...')
#10 /var/www/wordpress/wp-cli.phar(4): include('...')
#11 {main}
thrown in /var/www/wordpress/wp-admin/includes/class-wp-filesystem-ftpext.php on line 146
Fatal error: Uncaught TypeError: ftp_fget(): Argument #1 ($ftp) must be of type resource, null given in /var/www/wordpress/wp-admin/includes/class-wp-filesystem-ftpext.php:146
Stack trace:
#0 /var/www/wordpress/wp-admin/includes/class-wp-filesystem-ftpext.php(146): ftp_fget()
#1 /var/www/wordpress/wp-content/plugins/premiex-common/redux-framework-master/sample/sample-config.php(30): WP_Filesystem_FTPext->get_contents()
#2 /var/www/wordpress/wp-content/plugins/premiex-common/premiex-common.php(13): include('...')
#3 /var/www/wordpress/wp-settings.php(428): include_once('...')
#4 phar:///var/www/wordpress/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1336): require('...')
#5 phar:///var/www/wordpress/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1254): WP_CLI\Runner->load_wordpress()
#6 phar:///var/www/wordpress/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#7 phar:///var/www/wordpress/wp-cli.phar/vendor/wp-cli/wp-cli/php/bootstrap.php(78): WP_CLI\Bootstrap\LaunchRunner->process()
#8 phar:///var/www/wordpress/wp-cli.phar/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
#9 phar:///var/www/wordpress/wp-cli.phar/php/boot-phar.php(11): include('...')
#10 /var/www/wordpress/wp-cli.phar(4): include('...')
#11 {main}
thrown in /var/www/wordpress/wp-admin/includes/class-wp-filesystem-ftpext.php on line 146
Error: There has been a critical error on this website.Learn more about troubleshooting WordPress. There has been a critical error on this website.
[Error] Upgrade failed.
E: Unable to locate package wordpress-ynh-deps
```

**Comment by vsatmydynipnet** [comment]
ended_at: 2022-10-31 19:02:38.606027
env:
  BASH_XTRACEFD: '7'
  NO_BACKUP_UPGRADE: '0'
  YNH_APP_BASEDIR: /var/cache/yunohost/app_tmp_work_dirs/app_oawo8h15
  YNH_APP_CURRENT_VERSION: 6.0.2~ynh1
  YNH_APP_ID: wordpress
  YNH_APP_INSTANCE_NAME: wordpress
  YNH_APP_INSTANCE_NUMBER: '1'
  YNH_APP_MANIFEST_VERSION: 6.0.2~ynh2
  YNH_APP_UPGRADE_TYPE: UPGRADE_PACKAGE
  YNH_ARCH: amd64
  YNH_CWD: /var/cache/yunohost/app_tmp_work_dirs/app_oawo8h15/scripts
  YNH_INTERFACE: api
  YNH_STDRETURN: /tmp/tmp3533ular/stdreturn
error: Es ist ein Fehler im App-Upgrade-Skript aufgetreten
interface: api
operation: app_upgrade
parent: null
related_to:
- - app
  - wordpress
started_at: 2022-10-31 19:01:53.037305
success: false
yunohost_version: 11.0.10.2

============

**Comment by bernhardkaindl** [comment]
May be related to #191, but these versions are long obsolete. Would you close this PR, @vsatmydynipnet?
