### ISSUE TITLE
backup failed

### ISSUE THREAD

**Issue by tomdereub** [YunoHost-Apps/wordpress_ynh#48]
Hi,
Backup failed on my server : 

```
admin@lamo:/$ sudo yunohost backup create --apps wordpress -n test --method myborg --debug
[...]
2268 DEBUG + ynh_backup /etc/fail2ban/jail.d/wordpress.conf
2268 DEBUG + local SRC_PATH=/etc/fail2ban/jail.d/wordpress.conf
2268 DEBUG + local DEST_PATH=
2268 DEBUG + local IS_BIG=0
2268 DEBUG + BACKUP_CORE_ONLY=0
2268 DEBUG + '[' 0 == 1 ']'
2269 DEBUG + [[ -e /etc/fail2ban/jail.d/wordpress.conf ]]
2302 DEBUG + echo 'Source path '\''/etc/fail2ban/jail.d/wordpress.conf'\'' does not exist'
2302 DEBUG + return 1
2303 DEBUG + ynh_exit_properly
2302 WARNING Source path '/etc/fail2ban/jail.d/wordpress.conf' does not exist
2303 DEBUG + local exit_code=1
2304 DEBUG + '[' 1 -eq 0 ']'
2304 WARNING !!
2304 DEBUG + trap '' EXIT
2304 WARNING   wordpress's script has encountered an error. Its execution was cancelled.
2304 DEBUG + set +eu
2305 WARNING !!
2305 DEBUG + echo -e '!!\n  wordpress'\''s script has encountered an error. Its execution was cancelled.\n!!'
2305 WARNING
2305 DEBUG + type -t ynh_clean_setup
2305 DEBUG + ynh_die
2306 DEBUG + echo ''
2306 DEBUG + exit 1
2360 ERROR Impossible de sauvegarder l'application « wordpress »
Traceback (most recent call last):
  File "/usr/lib/moulinette/yunohost/backup.py", line 682, in _collect_app_files
    raise_on_error=True, chdir=tmp_app_bkp_dir, env=env_dict, user="root")
  File "/usr/lib/moulinette/yunohost/hook.py", line 381, in hook_exec
    errno.EIO, m18n.n('hook_exec_failed', path=path))
MoulinetteError: [Errno 5] Échec de l’exécution du script « /tmp/backup_jkMKrA »
2408 DEBUG action [686.1] executed in 2.184s
2408 DEBUG lock has been released
2409 ERROR Il n'y a rien à sauvegarder
```
I'm on yunohost 3, x64.

**Comment by maniackcrudelis** [comment]
Seems that there's a strange error with your fail2ban config. I don't know how it's possible that the file is missing.
Can you check the content of the directory, `ls -alh /etc/fail2ban/jail.d`

And, in order to fix the script, create a conf file for fail2ban. `sudo touch /etc/fail2ban/jail.d/wordpress.conf`

**Comment by JimboJoe** [comment]
I think it is due to a migration to Stretch: the migration just deletes the fail2ban configurations...

**Comment by tomdereub** [comment]
Here is the content of jail.d :

```
admin@lamo:~$ ls -alh /etc/fail2ban/jail.d/
total 16K
drwxr-xr-x 2 root root 4,0K juin  25 23:18 .
drwxr-xr-x 6 root root 4,0K juin  25 23:10 ..
-rw-r--r-- 1 root root   22 avril 17  2017 defaults-debian.conf
-rw-r--r-- 1 root root  397 juin  25 23:18 yunohost-jails.conf
```
After creating wordpress.conf in jail.d, I've had the same problem with fail2ban/filter.d :

```
admin@lamo:/etc/fail2ban/jail.d$ sudo ls -alh /etc/fail2ban/filter.d/
total 348K
drwxr-xr-x 3 root root 4,0K juin  25 23:17 .
drwxr-xr-x 6 root root 4,0K juin  25 23:10 ..
-rw-r--r-- 1 root root  442 déc.   9  2016 3proxy.conf
-rw-r--r-- 1 root root 3,2K déc.   9  2016 apache-auth.conf
-rw-r--r-- 1 root root 2,7K déc.   9  2016 apache-badbots.conf
-rw-r--r-- 1 root root 1,3K déc.   9  2016 apache-botsearch.conf
-rw-r--r-- 1 root root  813 déc.   9  2016 apache-common.conf
-rw-r--r-- 1 root root  268 déc.   9  2016 apache-fakegooglebot.conf
-rw-r--r-- 1 root root  487 déc.   9  2016 apache-modsecurity.conf
-rw-r--r-- 1 root root  596 déc.   9  2016 apache-nohome.conf
-rw-r--r-- 1 root root 1,2K déc.   9  2016 apache-noscript.conf
-rw-r--r-- 1 root root 2,0K déc.   9  2016 apache-overflows.conf
-rw-r--r-- 1 root root  346 déc.   9  2016 apache-pass.conf
-rw-r--r-- 1 root root 1014 déc.   9  2016 apache-shellshock.conf
-rw-r--r-- 1 root root 3,4K déc.   9  2016 assp.conf
-rw-r--r-- 1 root root 2,4K déc.   9  2016 asterisk.conf
-rw-r--r-- 1 root root  520 déc.   9  2016 botsearch-common.conf
-rw-r--r-- 1 root root 1,9K déc.   9  2016 common.conf
-rw-r--r-- 1 root root  252 déc.   9  2016 counter-strike.conf
-rw-r--r-- 1 root root  393 déc.   9  2016 courier-auth.conf
-rw-r--r-- 1 root root  490 déc.   9  2016 courier-smtp.conf
-rw-r--r-- 1 root root  443 déc.   9  2016 cyrus-imap.conf
-rw-r--r-- 1 root root  345 déc.   9  2016 directadmin.conf
-rw-r--r-- 1 root root 1,9K déc.   9  2016 dovecot.conf
-rw-r--r-- 1 root root 1,7K déc.   9  2016 dropbear.conf
-rw-r--r-- 1 root root  557 déc.   9  2016 drupal-auth.conf
-rw-r--r-- 1 root root 1,3K déc.   9  2016 ejabberd-auth.conf
-rw-r--r-- 1 root root  423 déc.   9  2016 exim-common.conf
-rw-r--r-- 1 root root 1,8K déc.   9  2016 exim.conf
-rw-r--r-- 1 root root 2,2K déc.   9  2016 exim-spam.conf
-rw-r--r-- 1 root root  963 déc.   9  2016 freeswitch.conf
-rw-r--r-- 1 root root 1,2K déc.   9  2016 froxlor-auth.conf
-rw-r--r-- 1 root root  236 déc.   9  2016 groupoffice.conf
-rw-r--r-- 1 root root  322 déc.   9  2016 gssftpd.conf
-rw-r--r-- 1 root root  512 déc.   9  2016 guacamole.conf
-rw-r--r-- 1 root root 1,2K déc.   9  2016 haproxy-http-auth.conf
-rw-r--r-- 1 root root  404 déc.   9  2016 horde.conf
drwxr-xr-x 2 root root 4,0K juin  25 23:10 ignorecommands
-rw-r--r-- 1 root root  482 déc.   9  2016 kerio.conf
-rw-r--r-- 1 root root  323 déc.   9  2016 lighttpd-auth.conf
-rw-r--r-- 1 root root 2,3K déc.   9  2016 mongodb-auth.conf
-rw-r--r-- 1 root root  773 déc.   9  2016 monit.conf
-rw-r--r-- 1 root root  652 déc.   9  2016 murmur.conf
-rw-r--r-- 1 root root  891 déc.   9  2016 mysqld-auth.conf
-rw-r--r-- 1 root root  400 déc.   9  2016 nagios.conf
-rw-r--r-- 1 root root 1,6K déc.   9  2016 named-refused.conf
-rw-r--r-- 1 root root  528 déc.   9  2016 nginx-botsearch.conf
-rw-r--r-- 1 root root  442 déc.   9  2016 nginx-http-auth.conf
-rw-r--r-- 1 root root 1,4K déc.   9  2016 nginx-limit-req.conf
-rw-r--r-- 1 root root  707 déc.   9  2016 nsd.conf
-rw-r--r-- 1 root root  459 déc.   9  2016 openhab.conf
-rw-r--r-- 1 root root  495 déc.   9  2016 openwebmail.conf
-rw-r--r-- 1 root root 1,9K déc.   9  2016 oracleims.conf
-rw-r--r-- 1 root root  814 déc.   9  2016 pam-generic.conf
-rw-r--r-- 1 root root  568 déc.   9  2016 perdition.conf
-rw-r--r-- 1 root root  834 déc.   9  2016 php-url-fopen.conf
-rw-r--r-- 1 root root  188 déc.   9  2016 portsentry.conf
-rw-r--r-- 1 root root 1,3K déc.   9  2016 postfix.conf
-rw-r--r-- 1 root root  454 déc.   9  2016 postfix-rbl.conf
-rw-r--r-- 1 root root  482 déc.   9  2016 postfix-sasl.conf
-rw-r--r-- 1 root root 1,2K déc.   9  2016 proftpd.conf
-rw-r--r-- 1 root root 2,4K déc.   9  2016 pure-ftpd.conf
-rw-r--r-- 1 root root  795 déc.   9  2016 qmail.conf
-rw-r--r-- 1 root root 1,3K déc.   9  2016 recidive.conf
-rw-r--r-- 1 root root 1,4K déc.   9  2016 roundcube-auth.conf
-rw-r--r-- 1 root root  821 déc.   9  2016 screensharingd.conf
-rw-r--r-- 1 root root  517 déc.   9  2016 selinux-common.conf
-rw-r--r-- 1 root root  570 déc.   9  2016 selinux-ssh.conf
-rw-r--r-- 1 root root  330 déc.   9  2016 sendmail-auth.conf
-rw-r--r-- 1 root root 2,4K déc.   9  2016 sendmail-reject.conf
-rw-r--r-- 1 root root  371 déc.   9  2016 sieve.conf
-rw-r--r-- 1 root root  706 déc.   9  2016 slapd.conf
-rw-r--r-- 1 root root  472 déc.   9  2016 sogo-auth.conf
-rw-r--r-- 1 root root 1,1K déc.   9  2016 solid-pop3d.conf
-rw-r--r-- 1 root root  206 déc.   9  2016 squid.conf
-rw-r--r-- 1 root root  199 déc.   9  2016 squirrelmail.conf
-rw-r--r-- 1 root root 3,1K déc.   9  2016 sshd.conf
-rw-r--r-- 1 root root  761 déc.   9  2016 sshd-ddos.conf
-rw-r--r-- 1 root root  363 déc.   9  2016 stunnel.conf
-rw-r--r-- 1 root root  645 déc.   9  2016 suhosin.conf
-rw-r--r-- 1 root root  821 déc.   9  2016 tine20.conf
-rw-r--r-- 1 root root  374 déc.   9  2016 uwimap-auth.conf
-rw-r--r-- 1 root root  637 déc.   9  2016 vsftpd.conf
-rw-r--r-- 1 root root  444 déc.   9  2016 webmin-auth.conf
-rw-r--r-- 1 root root  520 déc.   9  2016 wuftpd.conf
-rw-r--r-- 1 root root  503 déc.   9  2016 xinetd-fail.conf
-rw-r--r-- 1 root root  694 mars   9 04:00 yunohost.conf
```
Same solution, and now it works.

If the migration deletes the fail2ban configuration, does that mean that it's no more necessary ? Do I need to repair my fail2ban config or do you need to adapt backup script ?

Thanks

**Comment by lapineige** [comment]
Same issue for me, after migrating to Stretch. Same solution. I used an older backup to copy the content of both files into new `wordpress.conf` fail2ban config files.

**Comment by tomdereub** [comment]
Hi! Not exactly the same issue, but backup fail now for another reason : 
```
3608 WARNING !!! Source path '/etc/php/7.0/fpm/conf.d/20-wordpress.ini' does not exist !!!
3608 DEBUG + local SRC_PATH=/etc/nginx/conf.d/santequilibre.lamonerie.net.d/wordpress.conf
3609 WARNING !!
3609 DEBUG + local DEST_PATH=
3609 WARNING   wordpress's script has encountered an error. Its execution was cancelled.
```

**Comment by maniackcrudelis** [comment]
You're indeed suppose to have this file.
You can create a blank file to replace it for the backup script.

**Comment by tomdereub** [comment]
Actually I have this in /etc/php/7.0/fpm/conf.d : 
```
lrwxrwxrwx 1 root root  39 juin  25 23:17 10-mysqlnd.ini -> /etc/php/7.0/mods-available/mysqlnd.ini
lrwxrwxrwx 1 root root  39 juin  25 23:17 10-opcache.ini -> /etc/php/7.0/mods-available/opcache.ini
lrwxrwxrwx 1 root root  35 juin  25 23:17 10-pdo.ini -> /etc/php/7.0/mods-available/pdo.ini
lrwxrwxrwx 1 root root  35 juin  25 23:17 15-xml.ini -> /etc/php/7.0/mods-available/xml.ini
lrwxrwxrwx 1 root root  39 juin  25 23:18 20-apcu_bc.ini -> /etc/php/7.0/mods-available/apcu_bc.ini
lrwxrwxrwx 1 root root  36 juin  25 23:17 20-apcu.ini -> /etc/php/7.0/mods-available/apcu.ini
lrwxrwxrwx 1 root root  40 juin  25 23:17 20-calendar.ini -> /etc/php/7.0/mods-available/calendar.ini
lrwxrwxrwx 1 root root  37 juin  25 23:17 20-ctype.ini -> /etc/php/7.0/mods-available/ctype.ini
lrwxrwxrwx 1 root root  36 juin  25 23:17 20-curl.ini -> /etc/php/7.0/mods-available/curl.ini
lrwxrwxrwx 1 root root  35 juin  25 23:17 20-dom.ini -> /etc/php/7.0/mods-available/dom.ini
lrwxrwxrwx 1 root root  36 juin  25 23:17 20-exif.ini -> /etc/php/7.0/mods-available/exif.ini
lrwxrwxrwx 1 root root  40 juin  25 23:17 20-fileinfo.ini -> /etc/php/7.0/mods-available/fileinfo.ini
lrwxrwxrwx 1 root root  35 juin  25 23:17 20-ftp.ini -> /etc/php/7.0/mods-available/ftp.ini
lrwxrwxrwx 1 root root  34 juin  25 23:17 20-gd.ini -> /etc/php/7.0/mods-available/gd.ini
lrwxrwxrwx 1 root root  39 juin  25 23:17 20-gettext.ini -> /etc/php/7.0/mods-available/gettext.ini
lrwxrwxrwx 1 root root  37 juin  25 23:17 20-iconv.ini -> /etc/php/7.0/mods-available/iconv.ini
lrwxrwxrwx 1 root root  40 août  27 12:45 20-igbinary.ini -> /etc/php/7.0/mods-available/igbinary.ini
lrwxrwxrwx 1 root root  39 août  27 12:45 20-imagick.ini -> /etc/php/7.0/mods-available/imagick.ini
lrwxrwxrwx 1 root root  36 juin  25 23:18 20-intl.ini -> /etc/php/7.0/mods-available/intl.ini
lrwxrwxrwx 1 root root  36 juin  25 23:17 20-json.ini -> /etc/php/7.0/mods-available/json.ini
lrwxrwxrwx 1 root root  36 juin  25 23:17 20-ldap.ini -> /etc/php/7.0/mods-available/ldap.ini
lrwxrwxrwx 1 root root  40 juin  25 23:17 20-mbstring.ini -> /etc/php/7.0/mods-available/mbstring.ini
lrwxrwxrwx 1 root root  38 juin  25 23:17 20-mcrypt.ini -> /etc/php/7.0/mods-available/mcrypt.ini
lrwxrwxrwx 1 root root  38 juin  25 23:17 20-mysqli.ini -> /etc/php/7.0/mods-available/mysqli.ini
-rw-r--r-- 2 root root 189 sept. 29 23:41 20-nextcloud.ini
-rw-r--r-- 1 root root  42 sept.  4 11:54 20-opensondage.ini
lrwxrwxrwx 1 root root  41 juin  25 23:17 20-pdo_mysql.ini -> /etc/php/7.0/mods-available/pdo_mysql.ini
lrwxrwxrwx 1 root root  36 juin  25 23:17 20-phar.ini -> /etc/php/7.0/mods-available/phar.ini
lrwxrwxrwx 1 root root  37 juin  25 23:17 20-posix.ini -> /etc/php/7.0/mods-available/posix.ini
lrwxrwxrwx 1 root root  40 juin  25 23:17 20-readline.ini -> /etc/php/7.0/mods-available/readline.ini
lrwxrwxrwx 1 root root  37 août  27 12:45 20-redis.ini -> /etc/php/7.0/mods-available/redis.ini
lrwxrwxrwx 1 root root  37 juin  25 23:17 20-shmop.ini -> /etc/php/7.0/mods-available/shmop.ini
lrwxrwxrwx 1 root root  41 juin  25 23:17 20-simplexml.ini -> /etc/php/7.0/mods-available/simplexml.ini
lrwxrwxrwx 1 root root  39 juin  25 23:17 20-sockets.ini -> /etc/php/7.0/mods-available/sockets.ini
lrwxrwxrwx 1 root root  39 juin  25 23:17 20-sysvmsg.ini -> /etc/php/7.0/mods-available/sysvmsg.ini
lrwxrwxrwx 1 root root  39 juin  25 23:17 20-sysvsem.ini -> /etc/php/7.0/mods-available/sysvsem.ini
lrwxrwxrwx 1 root root  39 juin  25 23:17 20-sysvshm.ini -> /etc/php/7.0/mods-available/sysvshm.ini
lrwxrwxrwx 1 root root  41 juin  25 23:17 20-tokenizer.ini -> /etc/php/7.0/mods-available/tokenizer.ini
lrwxrwxrwx 1 root root  36 juin  25 23:17 20-wddx.ini -> /etc/php/7.0/mods-available/wddx.ini
-rw-r--r-- 1 root root   0 déc.  17 11:14 20-wordpress.ini
lrwxrwxrwx 1 root root  41 juin  25 23:17 20-xmlreader.ini -> /etc/php/7.0/mods-available/xmlreader.ini
lrwxrwxrwx 1 root root  41 juin  25 23:17 20-xmlwriter.ini -> /etc/php/7.0/mods-available/xmlwriter.ini
lrwxrwxrwx 1 root root  35 juin  25 23:17 20-xsl.ini -> /etc/php/7.0/mods-available/xsl.ini
lrwxrwxrwx 1 root root  35 juin  25 23:17 20-zip.ini -> /etc/php/7.0/mods-available/zip.ini
```

**Comment by maniackcrudelis** [comment]
So the file exist, but still you have this error about the file being missing ?

**Comment by tomdereub** [comment]
Ok, actually it works ! A friend has told me to do a `sudo touch /etc/php/7.0/fpm/conf.d/20-wordpress__2.ini`, I didn't understand what it did, but actually it has created the blank file.
Thanks !
